obj-$(CONFIG_PRIZE_LCD_BIAS) += lcd_bias/
obj-$(CONFIG_PRIZE_HALL) += hall/
obj-$(CONFIG_PRIZE_TORCH) += torch/
obj-$(CONFIG_PRIZE_BAROMETER_H5804) += h5804/
obj-$(CONFIG_PRIZE_FM_ANT_SWITCH) += fm_ant/
obj-$(CONFIG_PRIZE_SCR_RTL) += scr_rtl/

#prize added by chenjiaxi, prize_dual_camera driver, 20190111-start
obj-$(CONFIG_PRIZE_DUAL_CAMERA_ENABLE) += dual_camera/
#prize added by chenjiaxi, prize_dual_camera driver, 20190111-end

#prize added by chenjiaxi, prize_dual_camera_als driver, 20200922-start
obj-$(CONFIG_PRIZE_DUAL_CAMERA_ALS_ENABLE) += dual_camera_als/
#prize added by chenjiaxi, prize_dual_camera_als driver, 20200922-end

#prize added by huarui, haptic drv, 20190111-start
obj-$(CONFIG_PRIZE_HAPTIC_AW8695) += aw8695/
#prize added by huarui, haptic drv, 20190111-end

#prize-add prize-wangyunqing-20181110-start
obj-$(CONFIG_PRIZE_HARDWARE_INFO) += hardware_info/
#prize-add prize-wangyunqing-20181110-end

#prize added by zhaopengge, IRLED drv, 20200915-start
obj-$(CONFIG_PRIZE_LED_AW2028) += aw2028_led/
obj-$(CONFIG_PRIZE_LEDS_AW2015) += aw2015/
#prize added by zhaopengge, haptic drv, 20200915-end

#prize added by chenjiaxi, ir camera motor drv, 20201117-start
obj-$(CONFIG_PRIZE_IR_CAMERA_MOTOR) += ir_camera_motor/
#prize added by chenjiaxi, ir camera motor drv, 20201117-end