#
# Makefile for the SunnyCore touchscreen drivers.
#
# Each configuration option enables a list of files.

#obj-y	+= SC_ts.o fw_update.o

#ccflags-y += -Wall

obj-y +=  SC_ts.o
obj-y +=  fw_update.o
